---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'app'
        vault.hashicorp.com/agent-inject-secret-certs: 'pki/issue/marketplace'
        vault.hashicorp.com/agent-inject-template-certs: |
          {{- with pkiCert "pki/issue/marketplace" "common_name=app.marketplace.demo" "ttl=2h" -}}
          {{ .Cert }}{{ .CA }}{{ .Key }}
          {{ .Key | writeToFile "/vault/secrets/cert.key" "vault" "vault" "0644" }}
          {{ .Cert | writeToFile "/vault/secrets/cert.pem" "vault" "vault" "0644" }}
          {{- end -}}
    spec:
      serviceAccountName: app
      containers:
        - name: app
          image: nicholasjackson/fake-service:v0.26.0
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:443"
            - name: TLS_CERT_LOCATION
              value: "/vault/secrets/cert.pem"
            - name: TLS_KEY_LOCATION
              value: "/vault/secrets/cert.key"